import { generateUltimateSiteAsync } from './src/lib/ultimateTemplate.ts';
import { writeFileSync } from 'fs';

const leads = [
  {
    name: 'Electra Paris Électricité',
    sector: 'Électricien',
    city: 'Paris',
    phone: '+33 1 84 80 00 00',
    email: 'contact@electra-paris.fr',
    address: '12 Rue de Rivoli',
    googleRating: 4.8,
    googleReviews: 127,
    description: "Électricien certifié RGE intervenant à Paris pour dépannage, mise aux normes et domotique.",
    website: 'https://electra-paris.fr',
    hours: 'Lun-Ven 08h-19h · Sam 09h-13h',
    establishedYear: 2009,
    out: 'test-electricien-paris.html',
  },
  {
    name: 'Proxi Eau Plomberie',
    sector: 'Plombier',
    city: 'Lyon',
    phone: '+33 4 72 00 00 00',
    email: 'contact@proxieau.fr',
    address: '5 Cours Lafayette',
    googleRating: 4.6,
    googleReviews: 89,
    description: "Plombier chauffagiste à Lyon : dépannage urgence, fuites, rénovation salle de bain.",
    website: 'https://proxieau.fr',
    hours: 'Lun-Sam 07h30-20h',
    establishedYear: 2015,
    out: 'test-plombier-lyon.html',
  },
  {
    name: 'Coup de Ciseaux',
    sector: 'Coiffeur',
    city: 'Marseille',
    phone: '+33 4 91 00 00 00',
    email: 'contact@coupdeciseaux.fr',
    address: '18 La Canebière',
    googleRating: 4.7,
    googleReviews: 64,
    description: "Salon de coiffure à Marseille : coupe, coloration, balayage et soins.",
    website: 'https://coupdeciseaux.fr',
    hours: 'Mar-Sam 09h-19h',
    establishedYear: 2018,
    out: 'test-coiffeur-marseille.html',
  },
  {
    name: 'Saveur du Vieux Port',
    sector: 'Restaurant',
    city: 'Bordeaux',
    phone: '+33 5 56 00 00 00',
    email: 'contact@saveur-port.fr',
    address: '7 Quai des Chartrons',
    googleRating: 4.5,
    googleReviews: 203,
    description: "Restaurant gastronomique à Bordeaux : cuisine bordelaise et vins de la région.",
    website: 'https://saveur-port.fr',
    hours: 'Mar-Dim 12h-14h · 19h-22h',
    establishedYear: 2012,
    out: 'test-restaurant-bordeaux.html',
  },
  {
    name: 'Cabinet Dentaire Belmont',
    sector: 'Dentiste',
    city: 'Nantes',
    phone: '+33 2 40 00 00 00',
    email: 'contact@dentaire-belmont.fr',
    address: '22 Rue Crébillon',
    googleRating: 4.9,
    googleReviews: 156,
    description: "Dentiste à Nantes : soins, implants, orthodontie et esthétique dentaire.",
    website: 'https://dentaire-belmont.fr',
    hours: 'Lun-Ven 08h30-18h',
    establishedYear: 2005,
    out: 'test-dentiste-nantes.html',
  },
  {
    name: 'Avocat Lefèvre & Associés',
    sector: 'Avocat',
    city: 'Lille',
    phone: '+33 3 20 00 00 00',
    email: 'contact@lefevre-avocats.fr',
    address: '3 Place du Général de Gaulle',
    googleRating: 4.4,
    googleReviews: 38,
    description: "Avocat à Lille : droit des affaires, familial et immobilier.",
    website: 'https://lefevre-avocats.fr',
    hours: 'Lun-Ven 09h-18h',
    establishedYear: 2001,
    out: 'test-avocat-lille.html',
  },
  {
    name: 'Propre & Net Services',
    sector: 'Nettoyage',
    city: 'Toulouse',
    phone: '+33 5 61 00 00 00',
    email: 'contact@propre-net.fr',
    address: '40 Rue Alsace-Lorraine',
    googleRating: 4.6,
    googleReviews: 72,
    description: "Société de nettoyage à Toulouse : bureaux, copropriétés et vitrerie.",
    website: 'https://propre-net.fr',
    hours: 'Lun-Sam 07h-20h',
    establishedYear: 2016,
    out: 'test-nettoyage-toulouse.html',
  },
  {
    name: 'Vert Jardin Paysage',
    sector: 'Jardinier',
    city: 'Nice',
    phone: '+33 4 93 00 00 00',
    email: 'contact@vertjardin.fr',
    address: '15 Promenade des Anglais',
    googleRating: 4.7,
    googleReviews: 91,
    description: "Jardinier paysagiste à Nice : entretien, aménagement et taille.",
    website: 'https://vertjardin.fr',
    hours: 'Lun-Sam 08h-18h',
    establishedYear: 2010,
    out: 'test-jardinier-nice.html',
  },
  {
    name: 'Coach Forme Azur',
    sector: 'Coach sportif',
    city: 'Cannes',
    phone: '+33 4 93 00 11 11',
    email: 'contact@coachforme.fr',
    address: '9 Boulevard de la Croisette',
    googleRating: 4.8,
    googleReviews: 47,
    description: "Coach sportif à Cannes : remise en forme, musculation et suivi personnalisé.",
    website: 'https://coachforme.fr',
    hours: 'Lun-Sam 06h-21h',
    establishedYear: 2019,
    out: 'test-coach-cannes.html',
  },
  {
    name: 'Garage Auto Méridien',
    sector: 'Garage',
    city: 'Strasbourg',
    phone: '+33 3 88 00 00 00',
    email: 'contact@automeridien.fr',
    address: '11 Rue des Francs-Bourgeois',
    googleRating: 4.5,
    googleReviews: 118,
    description: "Garage automobile à Strasbourg : mécanique, entretien et contrôle technique.",
    website: 'https://automeridien.fr',
    hours: 'Lun-Ven 08h-18h · Sam 09h-12h',
    establishedYear: 2007,
    out: 'test-garage-strasbourg.html',
  },
];

for (const lead of leads) {
  const html = await generateUltimateSiteAsync(lead, undefined, '');
  writeFileSync(lead.out, html);

  const heroImg = (html.match(/<img[^>]*class="hero-bg"[^>]*src="([^"]+)"/) || html.match(/<img[^>]*src="([^"]+)"[^>]*class="hero-bg"/) || [])[1] || 'NONE';
  const iconMatch = html.match(/navbar-logo"><i data-lucide="([a-z-]+)"/);
  const checks = {
    file: lead.out,
    length: html.length,
    hasWhySection: html.includes('Pourquoi nous choisir'),
    noRealisations: !html.includes('Nos Réalisations'),
    hasFAQ: html.includes('Questions fréquentes') && html.includes(lead.city),
    fullNameShown: html.includes(lead.name),
    navbarIcon: iconMatch ? iconMatch[1] : 'NONE',
    noLogoInitialsBox: !new RegExp(`navbar-logo">[A-Z]{2}</div>`).test(html),
    hasReveal: html.includes('class="reveal'),
    noUndefined: !html.includes('undefined'),
    noNaN: !html.includes('NaN'),
    noAvisEnAttente: !html.includes('Avis en attente'),
    hasTrustBadge: html.includes('trust-badge'),
    whyUsTailored: !html.includes('Équipe Qualifiée'),
    heroImgIsImg: heroImg.startsWith('https://'),
  };
  console.log(JSON.stringify(checks, null, 2));
  console.log('HERO_IMG:', heroImg.slice(0, 100));
}
